### ISSUE TITLE
chrome extension 에 추가 방법이 궁금합니다 

### ISSUE THREAD

**Issue by ingjae** [snowdeer/better-review#1]
안녕하세요 . 
좋은 툴을 개발해 주셔서 감사합니다 
사용해보고 싶은데 chrome extension에 추가해보려 했으나 

![image](https://user-images.githubusercontent.com/52307552/235624264-35a60512-104d-43e4-8d7a-36260d2e952e.png)
Load 가 되지 않네요 

다른 방법이 있을까요 ?

**Comment by snowdeer** [comment]
안녕하세요.
스크린샷 봤을 때는 크롬 버전이 안 맞는 것 같은데,
현재 최신 버전의 크롬 사용하고 계시나요?
manifest v3 버전을 지원하는 크롬 버전에서
동작합니다.

감사합니다.

2023년 5월 2일 (화) 오후 6:00, injae hwang ***@***.***>님이 작성:

**Comment by ingjae** [comment]
답변 감사합니다.  
맥, 우분투 둘다 최신 버전으로 했는데 같은 오류가 발생 하네요   
 

![](https://user-images.githubusercontent.com/52307552/236119509-0d45724c-4761-4b5d-9271-f2f220c17868.png)

**Comment by snowdeer** [comment]
안녕하세요.
혹시 크롬 웹스토어에서 받으신거에요?
아니면, 소스 코드로 설치하신건가요?

크롬 웹스토어 버전은 정상 설치 되는거
확인했는데 소스 코드는 확인을
못해봤네요. ㅜㅜ

감사합니다!



2023년 5월 4일 (목) 오후 2:32, injae hwang ***@***.***>님이 작성:

**Comment by ingjae** [comment]
앗, 소스코드로 설치 했었습니다 
그렇군요 웹스토어 버전으로 사용해 보겠습니다 감사합니다 !
